### ISSUE TITLE
Installation error with Python 3

### ISSUE THREAD

**Issue by ghoshal** [marbl/metAMOS#186]
Hi,

I am trying to install a standalone version to metAmos and tried to follow the installation instructions. However I am getting errors regarding the python scripts in every step. Is there a way this can be avoided.

Thanks,

Bibaswan

**Comment by ghoshal** [comment]
I also tried using the 2to3 command to convert the files to python 3 mode. However, I am still getting error messages at different steps.

**Comment by skoren** [comment]
metAMOS has not been tested with Python 3 and it's likely not to work. If you can't install Python 2.7, I would recommend using the frozen binary instead.

**Comment by ghoshal** [comment]
Hi,

I installed python2.7 and ran the installation again. However this time I am getting a different error message. This is the error message I am getting.

Downloading http://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c11-py2.7.egg
Traceback (most recent call last):
  File "INSTALL.py", line 1701, in <module>
    use_setuptools()
  File "/data/biba/metAMOS-1.5rc3/Utilities/python/get_setuptools.py", line 103, in use_setuptools
    return do_download()       
  File "/data/biba/metAMOS-1.5rc3/Utilities/python/get_setuptools.py", line 97, in do_download
    egg = download_setuptools(version, download_base, to_dir, download_delay)
  File "/data/biba/metAMOS-1.5rc3/Utilities/python/get_setuptools.py", line 158, in download_setuptools
    src = urllib2.urlopen(url)
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/local/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>

Any help regarding this would be really appreciated.

Thanks,

Bibaswan

**Comment by skoren** [comment]
The error indicates setuptools installation cannot run on your system (the download is failing with a URL redirect).  I've verified the URL is correct and that I can run the setuptools installation. Does your system allow HTTP connections/downloads? Can you run wget http://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c11-py2.7.egg to see if you can download the file on your system?

**Comment by ghoshal** [comment]
I did the wget with --no-check-certificae option and the file was downloaded. I am trying to install it now.

**Comment by skoren** [comment]
Closing, will not support Python 3 in current releases of metAMOS.
