### ISSUE TITLE
StringIndexOutOfBoundsException during Preprocess

### ISSUE THREAD

**Issue by fwhelan** [marbl/metAMOS#221]
Sorry if this has been mentioned before- I couldn't find anything in closed issues.

I have Illumina, 300bp paired-end reads. I used cutadapt to trim the reads of any adapters, but no other manipulation has been done; I get the following error.

```
$ initPipeline -q -1 R1.fastq -2 R2.fastq -d out_metAMOS -i 300:500
$ runPipeline -d out_metAMOS -p 22 -a idba -c kraken -f Assemble,MapReads,FindORFS,Annotate,FunctionalAnnotation,Propagate,Classify,Abundance,FindScaffoldORFS,FunctionalAnnotation -g metagenemark
```

```
...
Last 10 lines of output (/home/sample/out_metAMOS/Logs/PREPROCESS.log)
rm: cannot remove ‘/home/sample/out_metAMOS/Preprocess/out/all.seq.mates’: No such file
 or directory
/usr/bin/python
/home/software/metAMOS-1.5rc3/Utilities/python:/home/software/metAMOS-1.5rc3/Utilities/ruffus:/home/software/metAMOS-1.5rc3/Utilities/python/lib:/home/software/metAMOS-1.5rc3/Utilities/python/lib/python:/home/software/metAMOS-1.5rc3/Utilities/python/lib64:/home/software/metAMOS-1.5rc3/Utilities/python/lib64
/python:/home/software/metAMOS-1.5rc3/Utilities:
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.charAt(String.java:658)
        at Utils.decodeQualRecord(Utils.java:232)
        at convertFastqToFasta.processFasta(convertFastqToFasta.java:38)
        at convertFastqToFasta.main(convertFastqToFasta.java:53)

Please veryify input data and restart MetAMOS. If the problem persists please contact the MetAMOS development team.
*************************ERROR***********************************
*****************************************************************
rm: cannot remove ‘/home/sample/out_metAMOS/Logs/preprocess.ok’: No such file or directory
Oops, MetAMOS finished with errors! see text in red above for details.
```

I can of course provide more information if this is novel. Thanks!
--Fiona

**Comment by skoren** [comment]
I think this is a new issue, my first guess from looking at the code is that there is a 0-length quality value in your fastq file (or the fastq file does not have 4 lines for one of the sequences). Can you check for those two cases?

**Comment by fwhelan** [comment]
You're right- I had an error further up the pipeline that produced 0 length quality values. I apologize!

Thanks for your help!
