### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by jerowe** [marbl/metAMOS#245]
```
[root@6d3896cca719 metAMOS-1.5rc3]# python INSTALL.py core
<<Welcome to metAMOS install>>
Traceback (most recent call last):
  File "INSTALL.py", line 68, in <module>
    import workflow
  File "/anaconda/conda-bld/work/metAMOS-1.5rc3/src/workflow.py", line 8, in <module>
    from utils import readConfigInfo
ImportError: cannot import name readConfigInfo
```

If I just do 

```
python setup.py build
python setup.py install
```

Running initPipeline.py (not initPipeline, btw, as it says in the docs) 

```
[root@6d3896cca719 metAMOS-1.5rc3]# initPipeline.py 
Traceback (most recent call last):
  File "/anaconda/bin/initPipeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('metAMOS==1.0b0', 'initPipeline.py')
  File "/anaconda/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 719, in run_script
  File "/anaconda/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 1511, in run_script
  File "/anaconda/lib/python2.7/site-packages/metAMOS-1.0b0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/initPipeline.py", line 13, in <module>

ImportError: No module named workflow
```

**Comment by skoren** [comment]
The install will copy initPipeline.py to initPipeline, you shouldn't be running initPipeline.py, that won't (and shouldn't) work.

My guess is you have a conflicting package that is being loaded instead of metAMOS's utils package. Try adding

```
import utils
print utils.__file__
import workflow
print workflow.__file__
```

on lines 67-68 in INSTALL.py. It should be

```
/anaconda/conda-bld/work/metAMOS-1.5rc3/src/utils.py
/anaconda/conda-bld/work/metAMOS-1.5rc3/src/workflow.py
```

If it's not try updating your python path to remove the offending utils package and try again.

**Comment by skoren** [comment]
Closing, inactivity
