### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by SilasK** [marbl/metAMOS#255]
Hello,

I ran in the following problem during the installation

```
g++ -Wall -fopenmp -O3 -c krakendb.cpp
/nihs/Software/gcc/gcc-4.7.1/bin/../libexec/gcc/x86_64-unknown-linux-gnu/4.7.1/cc1plus: error while loading shared libraries: libcloog.so.0: cannot open shared object file: No such file or directory
make: *** [krakendb.o] Error 1
Traceback (most recent call last):
  File "INSTALL.py", line 514, in <module>
    mem = utils.getAvailableMemory(settings)
  File "/nihs/Bioinformatics/nrc_hmi/Public/Programs/metAMOS-1.5rc3/src/utils.py", line 1283, in getAvailableMemory
    cacheusage = psutil.cached_phymem()
AttributeError: 'module' object has no attribute 'cached_phymem'
```

**Comment by SilasK** [comment]
I used an other version of python and it seems to work
