### ISSUE TITLE
During findorfs, the following command failed with return code -6

### ISSUE THREAD

**Issue by jtallman1** [marbl/metAMOS#260]
Hello,

When I try to run the program (at the runPipeline component), I get this error message at the "findorfs" step and I'm not sure what it means or what I should do to fix the issue:

*************************ERROR***********************************
During findorfs, the following command failed with return code -6:
>> /home/apps/metAMOS/1.5rc3/AMOS/Linux-x86_64/bin/toAmos_new -s /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.fna -b /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.fna.bnk

*************************DETAILS***********************************
Last 10 commands run before the error (/work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/Logs/COMMANDS.log)
|2017-02-26 21:52:35| ln /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/Assemble/out/soapdenovo.31.asm.contig /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/in/soapdenovo.31.asm.contig
|2017-02-26 22:04:51| /home/apps/metAMOS/1.5rc3/Utilities/cpp/Linux-x86_64/FragGeneScan -s /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/in/soapdenovo.31.asm.contig -o /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.orfs -w 0 -t complete
|2017-02-26 22:04:53| mv /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.orfs.ffn /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.ctg.fna
|2017-02-26 22:04:53| mv /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.orfs.faa /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.ctg.faa
|2017-02-26 22:04:53| mv /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.gene.cvg /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.ctg.gene.cvg
|2017-02-26 22:04:53| mv /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.gene.map /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.ctg.gene.map
|2017-02-26 22:04:53| rm -r /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.fna
|2017-02-26 22:04:54| cat /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31*.fna > /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.fna
|2017-02-26 22:04:54| rm -r /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.fna.bnk
|2017-02-26 22:17:12| /home/apps/metAMOS/1.5rc3/AMOS/Linux-x86_64/bin/toAmos_new -s /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.fna -b /work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.fna.bnk

Last 10 lines of output (/work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/Logs/FINDORFS.log)
no. of seqs: 496030
Read Bank doesn't exist; creating
frag Bank doesn't exist; creating
lib Bank doesn't exist; creating
parsing fasta file
terminate called after throwing an instance of 'AMOS::IOException_t'
  what():  Could not read bank, expected version: 3.0, saw version: 

Please veryify input data and restart MetAMOS. If the problem persists please contact the MetAMOS development team.
*************************ERROR***********************************
*****************************************************************
rm: cannot remove `/work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/Logs/findorfs.ok': No such file or directory
Oops, MetAMOS finished with errors! see text in red above for details.
Traceback (most recent call last):
  File "/home/apps/metAMOS/1.5rc3/runPipeline", line 991, in <module>
    verbose = 1)
  File "/home/apps/metAMOS/1.5rc3/Utilities/ruffus/task.py", line 2965, in pipeline_run
    raise job_errors
RethrownJobError: 
    
    
    Exception #1
      'exceptions.TypeError(exceptions must be old-style classes or derived from BaseException, not NoneType)' raised in ...
       Task = def findorfs.FindORFS(...):
       Job  = [soapdenovo.31.contig.cvg -> soapdenovo.31.faa]
    
    Traceback (most recent call last):
      File "/home/apps/metAMOS/1.5rc3/Utilities/ruffus/task.py", line 625, in run_pooled_job_without_exceptions
        return_value =  job_wrapper(param, user_defined_work_func, register_cleanup, touch_files_only)
      File "/home/apps/metAMOS/1.5rc3/Utilities/ruffus/task.py", line 491, in job_wrapper_io_files
        ret_val = user_defined_work_func(*param)
      File "/home/apps/metAMOS/1.5rc3/src/findorfs.py", line 392, in FindORFS
        run_process(_settings, "%s/toAmos_new -s %s/FindORFS/out/%s.fna -b %s/FindORFS/out/%s.fna.bnk"%(_settings.AMOS, _settings.rundir, _settings.PREFIX, _settings.rundir, _settings.PREFIX), "FindORFS")
      File "/home/apps/metAMOS/1.5rc3/src/utils.py", line 1154, in run_process
        raise
    TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
    
Thank you very much for your time! I greatly appreciate any help you can give me.

Thank you,
James

**Comment by skoren** [comment]
Can you check what the size of the ```/work/VibrioGenome/jtallman1/Thesis/MetAMOS_Output2/FindORFS/out/soapdenovo.31.fna``` file is? 

I suspect it is empty which is causing this issue.
