### ISSUE TITLE
Run test_phylosift.sh error

### ISSUE THREAD

**Issue by chen496** [marbl/metAMOS#263]
Hi, 

I've tried to run the example in metAMOS version 1.5rc3:  sh test_phylosift.sh
And then it shows the following error. Could you help me answer this question? 

```
Warning: BLASR is not found, some functionality will not be available
Warning: Newbler is not found, some functionality will not be available
Warning: MetaGeneMark is not found, some functionality will not be available
Warning: SignalP+ is not found, some functionality will not be available
Warning: PHmmer is not found, some functionality will not be available
Warning: R package is not found, some functionality will not be available
Warning: ALE is not found, some functionality will not be available
Warning: FRCbam is not found, some functionality will not be available
Warning: FreeBayes is not found, some functionality will not be available
Warning: MPI is not available, some functionality may not be available
Project dir /nethome/cxw496/software/src/metAMOS-1.5rc3/Test/test_phylosift successfully created!
Use runPipeline.py to start Pipeline
[Steps to be skipped]:  set(['FindRepeats'])
Starting Task = runpipeline.RUNPIPELINE
*** metAMOS running command: touch /nethome/cxw496/software/src/metAMOS-1.5rc3/Test/test_phylosift/Preprocess/in/carsonella_pe_filt.fna

Starting metAMOS pipeline
Found pysam in /share/opt/python/2.7.3/lib/python2.7/site-packages/RSeQC-2.3.9-py2.7-linux-x86_64.egg/pysam/__init__.pyc
Found psutil in /nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/python/lib/python/psutil-0.6.1-py2.7-linux-x86_64.egg/psutil/__init__.pyc
Warning: BLASR is not found, some functionality will not be available
Warning: Newbler is not found, some functionality will not be available
Warning: MetaGeneMark is not found, some functionality will not be available
Warning: SignalP+ is not found, some functionality will not be available
Warning: PHmmer is not found, some functionality will not be available
Warning: R package is not found, some functionality will not be available
Warning: ALE is not found, some functionality will not be available
Warning: FRCbam is not found, some functionality will not be available
Warning: FreeBayes is not found, some functionality will not be available
Warning: MPI is not available, some functionality may not be available
[Available RAM: 30 GB]
^[[^[[93m       There is *30 GB of RAM currently available on this machine, suggested minimum of 32 GB^[[0m
^[[^[[93m       *Enabling low MEM mode, might slow down some steps in pipeline^[[0m
^[[^[[93m       *If more RAM is available than what is listed above, please close down other programs and restart runPipeline^[[0m
[Available CPUs: 16]
^[[32m  *ok^[[0m
________________________________________
Tasks which will be run:

Task = preprocess.Preprocess
Task = assemble.SplitAssemblers
Task = assemble.Assemble
Task = assemble.CheckAsmResults
Task = assemble.SplitMappers
Task = mapreads.MapReads
Task = mapreads.CheckMapResults
Task = mapreads.SplitForORFs
Task = findorfs.FindORFS
Task = validate.Validate
Task = findreps.FindRepeats
Task = annotate.Annotate
Task = fannotate.FunctionalAnnotation
Task = scaffold.Scaffold
Task = findscforfs.FindScaffoldORFS
Task = abundance.Abundance
Task = propagate.Propagate
Task = classify.Classify
Task = postprocess.Postprocess
________________________________________
Warning: Graphviz is not found, some functionality will not be available
metAMOS configuration summary:
metAMOS Version:        v1.5rc3 "Praline Brownie"  workflows: core,optional,imetamos
Time and Date:          2017-03-31
Working directory:      /nethome/cxw496/software/src/metAMOS-1.5rc3/Test/test_phylosift
Prefix:                 proba
K-Mer:                  55
Threads:                8
Taxonomic level:        phylum
Verbose:                True
Steps to skip:          MultiAlign, FunctionalAnnotation, FindRepeats, FindScaffoldORFS
Steps to force:         Preprocess

[citation]
MetAMOS
        Treangen, TJ ⇔  Koren, S, Sommer, DD, Liu, B, Astrovskaya, I, Ondov, B, Darling AE, Phillippy AM, Pop, M. MetAMOS: a modular and open source metagenomic assembly and analysis pipeline. Genome biology, 14(1), R2, 2013.


Step-specific configuration:
[abundance]
MetaPhyler
        /nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
        Liu B, Gibbons T, Ghodsi M, Treangen T, Pop M. Accurate and fast estimation of taxonomic profiles from metagenomic shotgun sequences. BMC Genomics. 2011;12 Suppl 2:S4. Epub 2011 Jul 27.

[multialign]
M-GCAT
        /nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
        Treangen TJ, Messeguer X. M-GCAT: interactively and efficiently constructing large-scale multiple genome comparison frameworks in closely related species. BMC Bioinformatics, 2006.

[fannotate]
BLAST
        /nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
        Altschul SF, Gish W, Miller W, Myers EW, Lipman DJ. Basic local alignment search tool. J Mol Biol. 1990 Oct 5;215(3):403-10.

[scaffold]
Bambus 2
        /nethome/cxw496/software/src/metAMOS-1.5rc3/AMOS/Linux-x86_64/bin
        Koren S, Treangen TJ, Pop M. Bambus 2: scaffolding metagenomes. Bioinformatics 27(21): 2964-2971 2011.
[findorfs]
FragGeneScan
        /nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
        Rho M, Tang H, Ye Y: FragGeneScan: predicting genes in short and error-prone reads. Nucleic Acids Research 2010, 38:e191-e191.

[annotate]
PhyloSift
        /nethome/cxw496/software/src/metAMOS-1.5rc3/phylosift
        Darling, AE, Jospin, G, Lowe, E, Matsen IV, FA, Bik, HM, Eisen, JA. PhyloSift: phylogenetic analysis of genomes and metagenomes. PeerJ, 2, e243, 2014.

[assemble]
SOAPdenovo
        /nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
        Li Y, Hu Y, Bolund L, Wang J: State of the art de novo assembly of human genomes from massively parallel sequencing data.Human genomics 2010, 4:271-277.

[mapreads]
Bowtie
        /nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
        Langmead B, Trapnell C, Pop M, Salzberg SL. Ultrafast and memory-efficient alignment of short DNA sequences to the human genome. Genome Biol. 2009;10(3):R25. Epub 2009 Mar 4.

[preprocess]
metAMOS built-in filtering
        N/A

[validate]
LAP
        /nethome/cxw496/software/src/metAMOS-1.5rc3/LAP
        Ghodsi M, Hill CM, Astrovskaya I, Lin H, Sommer DD, Koren S, Pop M. De novo likelihood-based measures for comparing genome assemblies. BMC research notes 6:334, 2013.

[other]
Krona
        /nethome/cxw496/software/src/metAMOS-1.5rc3/KronaTools/bin
        Ondov BD, Bergman NH, Phillippy AM. Interactive metagenomic visualization in a Web browser. BMC Bioinformatics. 2011 Sep 30;12:385.
Starting Task = preprocess.PREPROCESS
*** metAMOS running command: java -cp /nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/java:.:. outputDefaultQuality /nethome/cxw496/software/src/metAMOS-1.5rc3/Test/test_phylosift/Preprocess/in/carsonella_pe_filt.fna > /nethome/cxw496/software/src/metAMOS-1.5rc3/Test/test_phylosift/Preprocess/in/carsonella_pe_filt.fna.qual

^[[^[[91m*****************************************************************
*************************ERROR***********************************
During preprocess, the following command failed with return code 127:
>> java -cp /nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/java:.:. outputDefaultQuality /nethome/cxw496/software/src/metAMOS-1.5rc3/Test/test_phylosift/Preprocess/in/carsonella_pe_filt.fna > /nethome/cxw496/software/src/metAMOS-1.5rc3/Test/test_phylosift/Preprocess/in/carsonella_pe_filt.fna.qual

*************************DETAILS***********************************
Last 10 commands run before the error (/nethome/cxw496/software/src/metAMOS-1.5rc3/Test/test_phylosift/Logs/COMMANDS.log)
|2017-03-31 14:45:54|# [RUNPIPELINE]
|2017-03-31 14:45:54| touch /nethome/cxw496/software/src/metAMOS-1.5rc3/Test/test_phylosift/Preprocess/in/carsonella_pe_filt.fna
|2017-03-31 14:46:02|# [PREPROCESS]
|2017-03-31 14:46:02| java -cp /nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/java:.:. outputDefaultQuality /nethome/cxw496/software/src/metAMOS-1.5rc3/Test/test_phylosift/Preprocess/in/carsonella_pe_filt.fna > /nethome/cxw496/software/src/metAMOS-1.5rc3/Test/test_phylosift/Preprocess/in/carsonella_pe_filt.fna.qual

Last 10 lines of output (/nethome/cxw496/software/src/metAMOS-1.5rc3/Test/test_phylosift/Logs/PREPROCESS.log)
/bin/bash: java: command not found

Please veryify input data and restart MetAMOS. If the problem persists please contact the MetAMOS development team.
*************************ERROR***********************************
*****************************************************************^[[0m
Oops, MetAMOS finished with errors! see text in red above for details.
                                                                       


rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/Test/test_phylosift/Logs/*.ok': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/Test/test_phylosift/Logs/preprocess.ok': No such file or directory
Traceback (most recent call last):
  File "../runPipeline", line 991, in <module>
    verbose = 1)
  File "/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 2965, in pipeline_run
    raise job_errors
RethrownJobError:

Exception #1
      'exceptions.TypeError(exceptions must be old-style classes or derived from BaseException, not NoneType)' raised in ...
       Task = def preprocess.Preprocess(...):
       Job  = [[carsonella_pe_filt.fna] -> preprocess.success]

    Traceback (most recent call last):
      File "/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 625, in run_pooled_job_without_exceptions
        return_value =  job_wrapper(param, user_defined_work_func, register_cleanup, touch_files_only)
      File "/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 491, in job_wrapper_io_files
        ret_val = user_defined_work_func(*param)
      File "/nethome/cxw496/software/src/metAMOS-1.5rc3/src/preprocess.py", line 185, in Preprocess
 run_process(_settings, "java -cp %s:. outputDefaultQuality %s/Preprocess/in/%s > %s/Preprocess/in/%s.qual"%(_settings.METAMOS_JAVA, _settings.rundir, read.fname, _settings.rundir, read.fname), "Preprocess")
      File "/nethome/cxw496/software/src/metAMOS-1.5rc3/src/utils.py", line 1154, in run_process
        raise
    TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
```

Thanks 

Chen

**Comment by skoren** [comment]
The error is listed in the output:
```/bin/bash: java: command not found```
Does your system have java installed. metAMOS requires at least version 6.0+ (http://metamos.readthedocs.io/en/v1.5rc3/content/installation.html)

**Comment by chen496** [comment]
@skoren Yes, Thank you for your reply. I have added my java path to my system. The error disappears.
I have rreferenced your examples in Test. I find that many of your files are paired read file or interleaved files. But My reads are non-paired and  when I run the command:
```
../initPipeline -f -1 test5.fna -d 41LH -i 70:80
../runPipeline -t eautils -a soap,velvet,spades,velvet-sc,sga,abyss,mira -c kraken -g fraggenescan -y -p 16 -d 41LH -f
Assemble,MapReads,FindORFS,Validate,FindRepats,FindScaffoldORFS,Abundance,Classify,Annotate,FunctionalAnnotation
```

And I get the following output:

```
Warning: BLASR is not found, some functionality will not be available
Warning: Newbler is not found, some functionality will not be available
Warning: MetaGeneMark is not found, some functionality will not be available
Warning: SignalP+ is not found, some functionality will not be available
Warning: PHmmer is not found, some functionality will not be available
Warning: ALE is not found, some functionality will not be available
Warning: FRCbam is not found, some functionality will not be available
Warning: FreeBayes is not found, some functionality will not be available
cp: cannot stat `test5.fna.qual': No such file or directory
Project dir /nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH successfully created!
Use runPipeline.py to start Pipeline
[Steps to be skipped]:  set(['FindRepeats'])
Starting Task = runpipeline.RUNPIPELINE
Starting metAMOS pipeline
Warning: BLASR is not found, some functionality will not be available
Warning: Newbler is not found, some functionality will not be available
Warning: MetaGeneMark is not found, some functionality will not be available
Warning: SignalP+ is not found, some functionality will not be available
Warning: PHmmer is not found, some functionality will not be available
Warning: ALE is not found, some functionality will not be available
Warning: FRCbam is not found, some functionality will not be available
Warning: FreeBayes is not found, some functionality will not be available
[Available RAM: 126 GB]
	*ok

________________________________________
Tasks which will be run:

Task = preprocess.Preprocess
Task = assemble.SplitAssemblers
Task = assemble.Assemble
Task = assemble.CheckAsmResults
Task = assemble.SplitMappers
Task = mapreads.MapReads
Task = mapreads.CheckMapResults
Task = mapreads.SplitForORFs
Task = findorfs.FindORFS
Task = validate.Validate
Task = findreps.FindRepeats
Task = annotate.Annotate
Task = fannotate.FunctionalAnnotation
Task = scaffold.Scaffold
Task = findscforfs.FindScaffoldORFS
Task = abundance.Abundance
Task = propagate.Propagate
Task = classify.Classify
Task = postprocess.Postprocess
________________________________________
Warning: Graphviz is not found, some functionality will not be available
metAMOS configuration summary:
metAMOS Version:	v1.5rc3 "Praline Brownie"  workflows: core,optional,imetamos
Time and Date:		2017-04-01
Working directory:	/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH
Prefix:			proba
K-Mer:			31
Threads:		16
Taxonomic level:	class
Verbose:		False
Steps to skip:		MultiAlign, FindRepeats
Steps to force:		Abundance, FunctionalAnnotation, FindORFS, Annotate, FindRepats, MapReads, Assemble, FindScaffoldORFS, Validate, Classify

[citation]
MetAMOS
	Treangen, TJ ⇔  Koren, S, Sommer, DD, Liu, B, Astrovskaya, I, Ondov, B, Darling AE, Phillippy AM, Pop, M. MetAMOS: a modular and open source metagenomic assembly and analysis pipeline. Genome biology, 14(1), R2, 2013.
Step-specific configuration:
[abundance]
MetaPhyler
	/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Liu B, Gibbons T, Ghodsi M, Treangen T, Pop M. Accurate and fast estimation of taxonomic profiles from metagenomic shotgun sequences. BMC Genomics. 2011;12 Suppl 2:S4. Epub 2011 Jul 27.

[multialign]
M-GCAT
	/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Treangen TJ, Messeguer X. M-GCAT: interactively and efficiently constructing large-scale multiple genome comparison frameworks in closely related species. BMC Bioinformatics, 2006.

[fannotate]
BLAST
	/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Altschul SF, Gish W, Miller W, Myers EW, Lipman DJ. Basic local alignment search tool. J Mol Biol. 1990 Oct 5;215(3):403-10.

[scaffold]
Bambus 2
	/nethome/cxw496/software/src/metAMOS-1.5rc3/AMOS/Linux-x86_64/bin
	Koren S, Treangen TJ, Pop M. Bambus 2: scaffolding metagenomes. Bioinformatics 27(21): 2964-2971 2011.

[findorfs]
FragGeneScan
	/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Rho M, Tang H, Ye Y: FragGeneScan: predicting genes in short and error-prone reads. Nucleic Acids Research 2010, 38:e191-e191.

[annotate]
Kraken
	/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/kraken/bin
	Wood DE, Salzberg SL: Kraken: ultrafast metagenomic sequence classification using exact alignments. Genome Biology 2014, 15:R46.

[assemble]
ABySS
	/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/abyss/bin
	Simpson, JT, Wong, K, Jackman, SD, Schein, JE, Jones, SJ, Birol, İ. ABySS: a parallel assembler for short read sequence data. Genome research, 19(6), 1117-1123, 2009.

SPAdes
	/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/spades/bin
	Anton Bankevich, Sergey Nurk, Dmitry Antipov, Alexey A. Gurevich, Mikhail Dvorkin, Alexander S. Kulikov, Valery M. Lesin, Sergey I. Nikolenko, Son Pham, Andrey D. Prjibelski, Alexey V. Pyshkin, Alexander V. Sirotkin, Nikolay Vyahhi, Glenn Tesler, Max A. Alekseyev, and Pavel A. Pevzner. Journal of Computational Biology. May 2012, 19(5): 455-477. doi:10.1089/cmb.2012.0021.

MIRA
	/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/mira/bin
	Chevreux, B, Wetter, T, Suhai, S. Genome Sequence Assembly Using Trace Signals and Additional Sequence Information. In German Conference on Bioinformatics (pp. 45-56), 1999.
SOAPdenovo
	/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Li Y, Hu Y, Bolund L, Wang J: State of the art de novo assembly of human genomes from massively parallel sequencing data.Human genomics 2010, 4:271-277.

SGA
	
	Simpson, JT, Durbin, R. Efficient de novo assembly of large genomes using compressed data structures. Genome Research, 22(3), 549-556, 2012.

Velvet
	/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/velvet
	Zerbino DR, Birney E. Velvet: algorithms for de novo short read assembly using de Bruijn graphs. Genome Res. 2008 May;18(5):821-9.

Velvet-SC
	/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/velvet-sc
	Chitsaz H, Yee-Greenbaum JL, Tesler G, Lombardo MJ, Dupont CL, Badger JH, Novotny M, Rusch DB, Fraser LJ, Gormley NA, Schulz-Trieglaff O, Smith GP, Evers DJ, Pevzner PA, Lasken RL. Efficient de novo assembly of single-cell bacterial genomes from short-read data sets. Nature Biotechnology, vol. 29, no. 11, pp. 915-921 (2011)

[mapreads]
Bowtie
	/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Langmead B, Trapnell C, Pop M, Salzberg SL. Ultrafast and memory-efficient alignment of short DNA sequences to the human genome. Genome Biol. 2009;10(3):R25. Epub 2009 Mar 4.
[preprocess]
EA-UTILS
	/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/eautils
	Aronesty E. TOBioiJ : "Comparison of Sequencing Utility Programs", DOI:10.2174/1875036201307010001, 2013.

[validate]
LAP
	/nethome/cxw496/software/src/metAMOS-1.5rc3/LAP
	Ghodsi M, Hill CM, Astrovskaya I, Lin H, Sommer DD, Koren S, Pop M. De novo likelihood-based measures for comparing genome assemblies. BMC research notes 6:334, 2013.

[other]
Krona
	/nethome/cxw496/software/src/metAMOS-1.5rc3/KronaTools/bin
	Ondov BD, Bergman NH, Phillippy AM. Interactive metagenomic visualization in a Web browser. BMC Bioinformatics. 2011 Sep 30;12:385.
Starting Task = preprocess.PREPROCESS
    Job  = [[test5.fna] -> preprocess.success] completed
Completed Task = preprocess.Preprocess
Starting Task = assemble.ASSEMBLE
    Job  = [preprocess.success -> *.run] completed
Completed Task = assemble.SplitAssemblers
Error: cannot run ABySS. Required PE library but not specified
    Job  = [abyss.31.run -> abyss.31.asm.contig] completed
    Job  = [mira.31.run -> mira.31.asm.contig] completed
Error: requested to run SGA (sga) but not available in specified location . Please check your specification and try again
    Job  = [sga.31.run -> sga.31.asm.contig] completed
    Job  = [soapdenovo.31.run -> soapdenovo.31.asm.contig] completed
    Job  = [spades.31.run -> spades.31.asm.contig] completed
    Job  = [velvet-sc.31.run -> velvet-sc.31.asm.contig] completed
    Job  = [velvet.31.run -> velvet.31.asm.contig] completed
Completed Task = assemble.Assemble
*** MetAMOS Warning: soapdenovo assembler did not run successfully!
*** MetAMOS Warning: velvet assembler did not run successfully!
*** MetAMOS Warning: spades assembler did not run successfully!
*** MetAMOS Warning: velvet-sc assembler did not run successfully!
*** MetAMOS Warning: sga assembler did not run successfully!
*** MetAMOS Warning: abyss assembler did not run successfully!
*** MetAMOS Warning: mira assembler did not run successfully!
** MetAMOS Error: no selected assembler ran successfully! Please check the logs in /nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Log/ASSEMBLE.log for details.
Oops, MetAMOS finished with errors! see text in red above for details.
```

This is the PREPROCESS.log

```
Picked up _JAVA_OPTIONS: -Xmx512m
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Preprocess/out/all.seq.mates': No such file or directory
Picked up _JAVA_OPTIONS: -Xmx512m
Command Line: -q 10 -t 0.01 -P 33 /nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/DB//adapter.fna -o /nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Preprocess/out/test5.fastq /nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Preprocess/in/test5.fastq
Scale used: 2.2
Phred: 33
Threshold used: 1 out of 10
No adapters found, no skewing detected, and no trimming needed.
Files: 1
Total reads: 10
Too short after clip: 0
Picked up _JAVA_OPTIONS: -Xmx512m
```

And this is  RUNPIPELINE.log

```
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/*.contig.cvg': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Logs/mapreads.ok': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Abundance/out/proba.taxprof.pct.txt': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Annotate/out/proba.hits': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Logs/validate.ok': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Validate/out/proba.asm.selected': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/*.faa': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/*.fna': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/FindORFS/out/*.fna': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Logs/assemble.ok': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/*.asm.contig': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Logs/classify.ok': No such file or directory
```

So could you help me? Or just give some suggestions? well, you know, metAMOS is very successful software. But the files or papers about metAMOS are not many. I am relly thank you for your team and your work.

Best wishes,

Chen

**Comment by skoren** [comment]
There's metAMOS documentation here: http://metamos.readthedocs.io/en/v1.5rc3

You shouldn't provide the paired-end size (-i) for unpaired reads. The error indicates none of the assemblers ran successfully, you would want to look at the ASSEMBLE.log file for details, as indicated by the error:
```
** MetAMOS Error: no selected assembler ran successfully! Please check the logs in /nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Log/ASSEMBLE.log for details.
```

**Comment by chen496** [comment]
OK, And I removed -i, the command is :

```
../initPipeline -f -1 test5.fna -d 41LH
../runPipeline -t eautils -a soap,velvet,spades,velvet-sc,sga,abyss,mira -c kraken -g fraggenescan -y -p 16 -d 41LH -f Assemble,MapReads,FindORFS,Validate,FindRepats,FindScaffoldORFS,Abundance,Classify,Annotate,FunctionalAnnotation
```

This is PREPROCESS.log

```
Picked up _JAVA_OPTIONS: -Xmx512m
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Preprocess/out/all.seq.mates': No such file or directory
Picked up _JAVA_OPTIONS: -Xmx512m
Command Line: -q 10 -t 0.01 -P 33 /nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/DB//adapter.fna -o /nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Preprocess/out/test5.fastq /nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Preprocess/in/test5.fastq
Scale used: 2.2
Phred: 33
Threshold used: 1 out of 10
No adapters found, no skewing detected, and no trimming needed.
Files: 1
Total reads: 10
Too short after clip: 0
Picked up _JAVA_OPTIONS: -Xmx512m
```

This is ASSEMBLE.log 

```
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/soapdenovo.31.asm.contig': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/soapdenovo.31.run': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/velvet.31.asm.contig': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/velvet.31.run': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/spades.31.asm.contig': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/spades.31.run': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/velvet-sc.31.asm.contig': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/velvet-sc.31.run': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/sga.31.asm.contig': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/sga.31.run': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/abyss.31.asm.contig': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/abyss.31.run': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/mira.31.asm.contig': No such file or directory
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/41LH/Assemble/out/mira.31.run': No such file or directory
```

And these are my reads(FASTA):

```
M00262:129:000000000-ATVBB:1:1101:19479:1979
CGCAAACTCTATAAACTCACTCCGGTTAAATACATGGTGAGATAATTGCTCCGAGCTTCAACTTAATAGT
>M00262:129:000000000-ATVBB:1:1101:15960:2117
GTGGTCAGGGGCTTGTGAGGGAGGAGCACGGGTGTCTTGGCAGCTGGGAAAGCCTGTCTCTTATACACAT
>M00262:129:000000000-ATVBB:1:1101:22120:2003
GAACGGAAAGGTAACTAGCGCAGACTACAGGGTGAGTCAGCGAATGCGAGTTAGCCAGAGGAGCGAGTGA
>M00262:129:000000000-ATVBB:1:1101:10314:1767
CTTCTAAAGTAGAGGCAATAGTTCCGTGTAAGTAGCCAGCCACCCCTGTGCCTGTCTCTTATACACATCT
>M00262:129:000000000-ATVBB:1:1101:23436:2106
GTATGTGAGTATACTGTGGCTGTCTTCAGACACATCAGAGAGGGCATCCTGTCTCTTATACACATCTCCG
>M00262:129:000000000-ATVBB:1:1101:8239:1774
GAAGTGGATTCATATTGTAGGGATCATTTATAGGAGAGAGAATGGGCATGCCTGTCTCTTATACACATCT
>M00262:129:000000000-ATVBB:1:1101:11865:1981
GTTTTTGGTGATGCTTCAAACCCAGTATCTTGTTCATGCTCGGGGCACCCTACCCTCTGTCTCTTATACA
>M00262:129:000000000-ATVBB:1:1101:18100:1864
GCCCTGTGTGCCCCTCCTCCAGCCACGACTGACTATAGACCTGTCTCTTATACACATCTCCGAGCCCACG
>M00262:129:000000000-ATVBB:1:1101:12051:1945
AGTGACAGCTGTGTCCCTTCCCTGCCCCTCCCAGCTCTCTTCCTGCTTTGTGGTATTTCTGTCTCTTATA
>M00262:129:000000000-ATVBB:1:1101:21717:1849
GATGTGTGCACAATGAAGAGAGTTGGAGCTGGAGACTCATGGTAGTGAGGAACAGTCTGATGTGAGTTGC
```

So I am confused, I am not sure whether my reads is not suitable to metAMOS? Thank you  very much

**Comment by skoren** [comment]
You can use metAMOS with unpaired reads. I'm confused when you say these are your reads? Is that all your data or a subset of it? If you can share your full dataset, I could run it locally to make sure it runs properly.

**Comment by chen496** [comment]
OK , I can share my data with you.

**Comment by chen496** [comment]
[51GHLH1.txt](https://github.com/marbl/metAMOS/files/887922/51GHLH1.txt)

Hi, Skoren,

Thank you very much. I have attached my file. Could you help me check it? Thank you for your time.

Chen

**Comment by skoren** [comment]
I ran through metAMOS with or without the -t option without error. I did have to rename the txt to fa or fasts. Here is the command I ran:
```
initPipeline -f -1 51GHLH1.fa -d 41LH
runPipeline -t eautils -a soap,velvet,spades,velvet-sc,sga,abyss,mira -c kraken -g fraggenescan -y -p 16 -d 41LH -v
```

**Comment by chen496** [comment]
Thank you, Skoren, could you attach the output files? the log file? I need to check my metAMOS, or reinstall it.

Best wishes,
Chen

**Comment by chen496** [comment]
Dear Skoren,

I really thank you for your help, it does work! And I use the command: 
python check_install.py /nethome/cxw496/software/src/metAMOS-1.5rc3 required_file_list.txt
I find some files are lost or paths have been changed, such as velvet and metavelvet.   I recorrect them, and it does good.  Maybe you need to refresh the  required_file_list.txt on next edition of metAMOS.

Thank you very much.
